### ISSUE TITLE
Incorrect Entity SQL generated when using FilterSettings directly from UserSetting.GetDefaultSettingsForUser

### ISSUE THREAD

**Issue by IanYates** [NullDesk/TicketDesk#100]
Following on from issue #99 - I am using UserSetting.GetDefaultSettingsForUser to get appropriate defaults for the "unassigned" list settings for the user.

The problem best given as an example of data flowing through `TicketCenterListViewModel.ListTicketsAsync`.  For a working user, where the settings JSON was loaded from the database, the filterColumns list has two entries, and it's the second one that tries to filter by "AssignedTo".  This is `null` for the working user and generates appropriate EntitySQL like

```
SELECT VALUE it
FROM (
SELECT VALUE it
FROM (
[TdDomainContext].[Tickets]
) AS it
WHERE
it.TicketStatus != @TicketStatus and it.AssignedTo = @AssignedTo
) AS it
ORDER BY
it.LastUpdateDate DESC
```

But for a non-working user, filterColumns list still has two entries, and the second one filters by "AssignedTo" but it's filtering for `DBNull.Value'.  That causes the following incorrect EntitySQL to be generated - it fails on the IS

```
SELECT VALUE it
FROM (
SELECT VALUE it
FROM (
[TdDomainContext].[Tickets]
) AS it
WHERE
it.TicketStatus != @TicketStatus and it.AssignedTo IS @AssignedTo
) AS it
ORDER BY
it.LastUpdateDate DESC
```

This is because the constructor used for `UserTicketListFilterColumn` replaces a null column value with DBNull.Value.  However if it's initialised via the JSON loaded from the database then (I haven't double-checked this) a different constructor is used and the properties are directly set.  The property setting doesn't convert an incoming null to DBNull.Value so we get to keep our null and our working EF query.

My suggested fix is to remove the `?? DBNull.Value` but I'm not sure what other effects this would have on the codebase.

Quick watch on working filterColumns
![ticketdesk_1](https://cloud.githubusercontent.com/assets/1314477/9293180/88ab0286-4463-11e5-8bff-ccda30ba3dbb.PNG)

And on broken filterColumns

![ticketdesk_2](https://cloud.githubusercontent.com/assets/1314477/9293182/9212e9d8-4463-11e5-81e8-b650ef0880f9.PNG)

**Comment by IanYates** [comment]
So far the change seems to be Ok. 

However I think perhaps a better fix could be made to `UserSettingExtensions.ApplyToQuery` so that it better handles the case where the value is DBNull.Value.  I've made this change to the code
```
            var filterColumns = filters.ToList();
            if (filterColumns.Count > 0)
            {
                //maximum capacities - we may not use all of fParams though if NULLs are encountered
                var fkeys = new List<string>(filterColumns.Count);
                var fParams = new List<ObjectParameter>(filterColumns.Count);
                for (var i = 0; i < filterColumns.Count; i++)
                {
                    string optr;
                    var filterColumn = filterColumns[i];

                    if (filterColumn.ColumnValue == DBNull.Value || filterColumn.ColumnValue == null)
                    {
                        optr = (filterColumn.UseEqualityComparison.HasValue && !filterColumn.UseEqualityComparison.Value)
                            ? "IS NOT NULL"
                            : "IS NULL";

                        fkeys.Add(string.Format("it.{0} {1}", filterColumn.ColumnName, optr));
                    }
                    else
                    {
                        optr = (filterColumn.UseEqualityComparison.HasValue && !filterColumn.UseEqualityComparison.Value)
                            ? "!="
                            : "=";

                        fkeys.Add( string.Format("it.{0} {1} {2}", filterColumn.ColumnName, optr, "@" + filterColumn.ColumnName));

                        //most of the time esql works with whatever type of param value you pass in, but
                        // enums in our collection are serialized to/from json as integers.
                        // Check if enum, and explicitly convert int value to the correct enum value
                        if (filterColumn.ColumnValueType != null && filterColumn.ColumnValueType.IsEnum)
                        {
                            filterColumn.ColumnValue = Enum.Parse(filterColumn.ColumnValueType, filterColumn.ColumnValue.ToString());
                        }
                        //assigning the type in ctor, then value directly as a param works around issues when the colum val is null.
                        fParams.Add(
                            new ObjectParameter(filterColumn.ColumnName, filterColumn.ColumnValueType)
                            {
                                Value = (filterColumn.ColumnValue == DBNull.Value) ? null : filterColumn.ColumnValue
                            }
                            );
                    }
                    

                }

                var wString = string.Join(" and ", fkeys);
                baseQuery = baseQuery.Where(wString, fParams.ToArray());
            }
            return baseQuery;
        }
```

However I'm again not entirely sure whether or not the null should be handled this way in all cases...  I think the first fix above is more targeted since it just addresses this specific issue (so ought not to affect other things) but this one (or some variation of it) is probably a better overall fix.

Happy to create a PR after the discussion :)

**Comment by StephenRedd** [comment]
I'll need to dig into this a little deeper. I don't see any obvious problem with your fix (the second), but I would like to look at what's going on with the serialization and deserialization of these settings in the first place.

It seems to me that the root of the problem is that when filterColumn comes from the default setting generator, then it differs from a filterColumn that was loaded via serialized json from the DB. This is where I'd want to make the patch. 

The property value should be set the same way, no matter how the object is actually instantiated or where the parameter data came from.  

It really doesn't matter if we're using DBNull.Value or C# null; we can handle either in the ESQL part (it's just the difference between the "is" operator and the "=" operator). But, I'm not necessarily keen on supporting both possibilities. We should make sure the filterColumn is always DBNull.Value, or always c# null; then handle just that one case in the apply filter. 

Thanks for taking a look! I'll go ahead and put this on the schedule, but it might be a few days before I get back to it. If you have more time, feel free to take a look and send a pull request.

**Comment by StephenRedd** [comment]
I'm going to take a stab at just removing the dbnull variation. Since it appears that DB initialization is keeping the value as just null, and EF seems to handle that well via the = comparison, it makes more sense to uniformly use C# null everywhere.

If you get time to retest, I'd appreciate it. I've done my own testing, and it seems fine; but I'd never satisfactorily been able to reproduce the original problem; so I can't be sure my testing covered all the cases that were reported.

**Comment by IanYates** [comment]
Hi @StephenRedd - I haven't got my TicketDesk server up and running at the moment but will update it in the coming week and see how things run.  It's been a while so I can't exactly remember how to reproduce it all now either :)

**Comment by StephenRedd** [comment]
thanks! I've made a number of related fixes too, so hopefully this is good to go.
