### ISSUE TITLE
Global.asax Excluded from Project

### ISSUE THREAD

**Issue by clockwiseq** [NullDesk/TicketDesk#106]
Someone excluded the Global.asax from the Web.Client project and causes the application to fail when debugging/running.

**Comment by StephenRedd** [comment]
This is an owin/katana hosted application, so all of the initilization is handled through the startup.cs instead of a global.asax. Most likely, the startup problems you are experiencing have another cause, but we'll need more information about the actual failure conditions to diagnose the cause.

**Comment by sgwill** [comment]
I had this issue, too, when I pulled from master today (11/17/2015). Even though `global.asax` and `global.asax.cs` are excluded from the projec,t IIS/IIS Express still attempts to run `global.asax` if it's in the directory. Since `global.asax.cs` isn't part of the project, the code behind is not included in the build which causes the runtime issue.

It looks like the only code in `global.asax.cs` is setting the Culture cookie. It looks like that's being handled in the LocalizationFilter. I think if you delete the `global.asax` and `global.asax.cs` from the project, the issue will be resolved.

**Comment by StephenRedd** [comment]
Those totally snuck in on me, probably during the pull request merge. My apologies. Since I always deploy via the publish feature, or though kudu's CI, I've never had the problem of those files being copied to production. 

I appreciate you keeping me straight on it.
