### ISSUE TITLE
sending ticket mail 

### ISSUE THREAD

**Issue by rhan55** [NullDesk/TicketDesk#134]
i'm configure Push notification settings and i use SMTP Provider (Email) . when record a ticket or edit a ticket is not sending e-mail . 

my SMTP settings is right, i use it different sites.

**Comment by StephenRedd** [comment]
Yeah, a lot of that being reported. I'm preparing to gut the entire notification system and re-implement it using the [NullDesk Mailer Extensions](https://github.com/NullDesk/NullMailer). Since it's been a while since I was able actively move the project forward, there will be quite a number of changes when the work picks back up again.

**Comment by dak1220** [comment]
I just discovered TicketDesk today, and downloaded the latest version from the develop branch. I love the interface and I think we would love to move forward on implementing some custom changes for our specific needs, but the email issue is holding us back a bit. @StephenRedd, I traced around the source code for a while and it seems as though the problem might lie in the `SendNextReadyNotificationAsync()` function in `PushNotificationDeliveryManager.cs`. In that function the variable `readyNote` is always null in my testing and thus the `SendNotificationMessageAsync()` function is never reached. Perhaps this is a red herring, but I thought I would include this message as a starting point in case development picks up again, which I hope it does :+1: TicketDesk is fantastic!

**Comment by StephenRedd** [comment]
If you don't mind, can you tell me if you are planning to use TicketDesk deployed to on-prem servers or in Azure?  I have some time coming up to spend on TicketDesk, and I'm working out how I want to move forward. I'm fairly certain that I will not complete all the originally planned TD 2.5 features. Instead, I want to leave TD 2.5 in a stable state with the current feature set, then move on to TD 3. One of the options I'm considering then, is to pull the Azure feature set out of TD 2..5 and just focus on completing the on-prem functionality. Most of the Azure features were early beta when they were written, and I'd have a lot of re-work to do just to bring those features in TD 2.5 up to date with the current Azure libraries... and that's time I'd rather spend on a fully modern version instead. But any community input on the matter would be greatly appreciated.

**Comment by dak1220** [comment]
We are interested in on-prem servers, mainly for the extra layer of security that offers, but I am not sure what the rest of the user base will think on this issue. For the foreseeable future, I don't see us using Azure. Thanks for the reply! I hope I could help!

**Comment by StephenRedd** [comment]
Thanks for the info.  

I have finally been able to locate and repair the main problem that seems to have been plaguing the email notifications --a fairly nasty combination of threading, async, and DI lifecycle management issues. 

If you get time to test it, please report back if there are any outstanding issues with it.

**Comment by dak1220** [comment]
I tested this some yesterday, and the change did not seem to fix the specific issue I am having. I am not completely sure that the problem isn't in the settings I am using for SMTP. I will do more research after I finish some modifications to the Ticket to suit our custom needs. I will report back if I am still having the issue, hopefully with some specifics to help with diagnosis. Thanks for the fix! I hope the problem is my configuration!

**Comment by jeffkenn2000** [comment]
Is there an update that will work in version 2.5?   I see the pushnotificationdeliverymanager, but it doesnt seem to be wired up.
