### ISSUE TITLE
Push Notifications not populating

### ISSUE THREAD

**Issue by joedavis01** [NullDesk/TicketDesk#139]
I am running this application on server 2012  with Sql 2014 and framework 4.6.2. 
for the life of me I cannot get the push notifications to fire.. I have monitored all the notifications tables and nothing gets populated on ticket creation or update.

I have unchecked the Exclude Subscriber and Notification Consolidation to make sure nothing was getting filtered, but still no go.. 

I have another application that uses our notification server so I am extremely confident the smtp settings

**Comment by MKapitancik** [comment]
Hello, I'm running same setting as mentioned by @joedavis01. I deployed site on IIS 8.0 web server and configured it with SMTP delivery provider. Mails was not working, but on localhost everything seems fine.

I resolved it by changing registration of notification in _Startup.PushNotifications.cs_ don't use HostingEnvironment.QueueBackgroundWorkItem there. After that mails starts working

**Comment by StephenRedd** [comment]
Is your server running .NET 4.6.1 or .NET 4.6.2?

**Comment by joedavis01** [comment]
4.6.1

**Comment by joedavis01** [comment]
I read your comments before on the issues with 4.6.2 so we didnt upgrade

**Comment by StephenRedd** [comment]
4.6.2 was re-released around the time that VS 2017 came out; it should be fine to use it now. 

I'm very perplexed by the fact that this is still not working in your cases. The recent changes I made in this area seem rock-solid, and I was able to positively identify and fix the cause of earlier problems in this area. 

As of right now, I can find no particular reason why deploying to IIS 8 would cause this to behave differently. I'm not a big fan of having this code run on the main thread, but it isn't horridly slow either; maybe it would be better to just do away with backgrounding this task and be done with it?

Would you be able to send a pull request with your update?

**Comment by mguinness** [comment]
@MKapitancik Would you be able to share your code changes?  Are you just commenting out the QueueBackgroundWorkItem block in [Startup.PushNotifications.cs](https://github.com/NullDesk/TicketDesk/blob/develop/TicketDesk/TicketDesk.Web.Client/App_Start/Startup.PushNotifications.cs#L67)?

**Comment by MKapitancik** [comment]
We are simply doing registration on main thread (comment line QueueBackgroundWorkItem) this solve our issues with emails, when deploying to IIS.
We haven't found any reason why QueueBackgroundWorkItem doesn't work there. 
I thinks it may be something related when pool is starning, but I didn't do any analysis and im not an IIS expert.

**Comment by mguinness** [comment]
@MKapitancik Thanks for your reply.  Actually this wasn't broken for us, but rather it was a failure to understand how push notifications work.

What I need is that when new tickets are created an email is sent to "Help Desk Staff".

@StephenRedd If I added a trigger to the Tickets table, is there a way to insert records into the ticket event notifications tables to achieve this?  Any guidance would be appreciated.

**Comment by StephenRedd** [comment]
@mguinness This is a perfectly valid approach to get the behavior you want without adding new code. It is clever, and a low-impact solution. It also wouldn't interfere with your ability to update the code for future releases.

Obviously the [broadcast notification](https://github.com/NullDesk/TicketDesk/issues/50) feature that was originally planned would take a code-first approach instead of relying on DB logic; but that does not invalidate your solution at all. 

Since there seems to be a bit of community interest in this still, I will see about getting some free time over the next couple of weeks to complete the most important of the notification related features.

**Comment by StephenRedd** [comment]
@MKapitancik It is indeed unusual that the background thread doesn't in your environment. Perhaps the best approach would be to have a setting that allows the admin to choose to use background tasks or not?

**Comment by AGitDev** [comment]
I too found that the push notifications were not populating when attempting to use a background thread (running as localhost on IIS10, which may be the reason). To get working change the following line (69) in Startup.PushNotifications.cs 
from
` HostingEnvironment.QueueBackgroundWorkItem(ct => {'
to
` Task.Run(() => {`
  
 Hope this helps Stephen as a temporary fix for people.

**Comment by mguinness** [comment]
@StephenRedd Thanks for your efforts on this project.  I'm also running IIS 10, but the notifications are running intermittently - nothing new going into PushNotificationItems table.  I tried enabling always running for the app pool but that had no effect.  I will try the suggestion from AGitDev which should help.  As you mentioned maybe an entry in appSettings would be a good compromise.

**Comment by StephenRedd** [comment]
Part of the problem here could be related to how TD was creating the admin account during first-run-setup; it not registering the user as an email recipient in the notification system. In the debugger, I ran into cases where an exception would be thrown for some notifications when being queued up for the admin user.

**Comment by ErickP24** [comment]
Hello, I deployed TicketDesk on IIS 8 and I didn't receive email notifications, I use 587 port to config email notifications, when I test on localhost I receive the message but when I publish system on IIS it doesn't work.
Could you help me to fix this issue?

**Comment by StephenRedd** [comment]
It is very difficult to troubleshoot such an issue with limited information. This could be a firewall issue if you are trying to connect out to a remote SMTP relay server. I would recommend getting a simple development SMTP testing service like [papercut](https://github.com/ChangemakerStudios/Papercut) and install it on the local server -- configure ticketdesk for localhost port 25 on that system, and verify first if ticketdesk itself is actually able to send email. If so, the problem is network or similar; if not the problem is ticketdesk itself. But narrowing down where to look is the first step
