### ISSUE TITLE
Solution build failed

### ISSUE THREAD

**Issue by workcontrolgit** [NullDesk/TicketDesk#144]
After git clone version 2.5.2, unable to build the solution using VS 2015.  The project PushNotifications failed to build.  Was able to build 2.5.1 with VS 2015.

**Comment by huntertran** [comment]
install this nuget package to TicketDesk.PushNotification project and build again
[https://www.nuget.org/packages/Microsoft.Net.Compilers/](https://www.nuget.org/packages/Microsoft.Net.Compilers/)

The reason is that some code is using C# 7.0 syntax, which is not supported by default with VS 2015 compiler

**Comment by StephenRedd** [comment]
Do you have update 3 or higher for VS 2015 installed?

**Comment by workcontrolgit** [comment]
I was able to build 2.5.2 with VS 2017

**Comment by workcontrolgit** [comment]
I have update 3 for VS 2015 installed.

**Comment by huntertran** [comment]
@StephenRedd yes, I always have latest version of Visual Studio 2015 installed
@workcontrolgit can you build it with VS 2015?
