### ISSUE TITLE
POP \ Email Responses 

### ISSUE THREAD

**Issue by mPisano** [NullDesk/TicketDesk#161]
First off, Great Project!

I'm still learning the feature set, but I don't see anyway for the reply emails to get aggregated back into the database thread? 

Am I missing anything?

Thanks,
Mike

**Comment by StephenRedd** [comment]
TD has never supported incoming email. The functionality necessary to support incoming emails varies quite drastically depending on the kind of mail technology used. It is also exceptionally difficult to create a comprehensive feature set that would fit everyone, or a feature set that could be easily customized to fit anyone. Besides, the whole point of TD is to make discussing tickets easy and fluid, and to encourage users to have those discussions in TD, not have the discussions over email.

It's fairly easy to add incoming mail support yourself, and since you would know which mail server type you use, what protocol you have available, and what rules you want use to handle any incoming email, it is fairly straight forward to code up basic support.

**Comment by mPisano** [comment]
I agree, but mail is sent as the generic outbound account so If people reply then it looks like it it would just sit in an unmanaged mailbox. I could make the outbound mail send as the users email address, but then the replies would be outside TD and untracked.

So many users are accustomed to grabbing their phone and sending replies, I don't want them to wait and use TD. I know bootstrap and the css should scale - how easy is it to use TD on an iphone? 

I think I will add this feature, I see S22 has Imap built in, I would of prefered POP3, so I might add OpenPop. OpenPop also has Mime handling so i'm not sure S22 would still be necessary...
I will also have a look at some other open source projects and how they handle the mime content and dupe elim the outbound thread to only add the newer response to the DB.

Regards,
Mike

**Comment by StephenRedd** [comment]
Most people would set the from address to "noreply@xxx.yyy" or some such, and perhaps have an auto-responder in case someone does email back. But if you want to handle the incoming mail, it really isn't too difficult... and there are tons of libraries that help. Personally, I tend to use MailKit for my commercial projects that need this kind of functionality.

As I said though, the reason that's not out-of-box functionality is the sheer complexity of supporting general purpose features around it in a way that makes sense for the community as a whole, while also handling the broad range of mail protocols, auth schemes, and service APIs. Just too many technologies, and too many routing and workflow rules to make it a priority feature set for the OSS version (so far anyway). Things get a whole lot simpler when you can just code to a set of known requirements and technologies for your specific environment though.

**Comment by mPisano** [comment]
I sent you an PM to your domain yesterday that better explains...
