### ISSUE TITLE
Error 'write.lock' cannot access because it is being used by another process

### ISSUE THREAD

**Issue by ultramanbank** [NullDesk/TicketDesk#168]
When i click resolve ticket website has error below:

Server Error in '/' Application.

The process cannot access the file '{Web path}\write.lock' because it is being used by another process.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IO.IOException: The process cannot access the file '{Web path}\write.lock' because it is being used by another process.

**Comment by StephenRedd** [comment]
This is a failure to write to the search indexes because there is already a lock file -- so it thinks another process is writing to the index (which may or may not actually be true). Delete the lock file manually, and also make sure you IIS application pool user has full access to the /app_data folder.

**Comment by jeffkenn2000** [comment]
I'm getting the same thing but I don't see a lock file in the directory. Any idea's?

**Comment by StephenRedd** [comment]
Permissions would be the most likely cause of an issue like that.

**Comment by jeffkenn2000** [comment]
You exactly right. It was the user for the app pool, not the site.

Thanks

**Comment by StephenRedd** [comment]
Glad you got it resolved. Normally that's not a problem, since the std behavior is usually for the app pools with the std app pool identity will give the pool write access to app_data; but some server environments are configured differently; and if you use a custom app pool identity, I believe you have to manually assign those permissions.

**Comment by ultramanbank** [comment]
@StephenRedd 

I add permission full control to folder website. i', getting error always.

![error_1](https://user-images.githubusercontent.com/785300/41148497-52fc4c40-6b33-11e8-8ca9-ddd78556565b.jpg)

![error_2](https://user-images.githubusercontent.com/785300/41148505-57d6079c-6b33-11e8-9cf3-c646eb3bfdea.jpg)
