### ISSUE TITLE
Active Directory In 2.5

### ISSUE THREAD

**Issue by HenryTr88** [NullDesk/TicketDesk#176]
I know AD has been disabled in 2.5, but is there a quick way to enable this?  I'm fairly new to web development and trying to get a grasp of how difficult it would be to get this to work.   There was a previous question asked about this, however I don't need to worry about signing on from outside the network.

**Comment by StephenRedd** [comment]
The difficulty in supporting integration with AD has always been the mapping of groups in AD to Roles in ticketdesk. Older versions of TicketDesk has some scary ADSI code and could handle those mappings for most domains (as long as AD wasn't too customized, or using a complex forest arrangement). But this is ill-advised code these days, and it doesn't perform very well anyway. That's why it was never implemented for newer TD versions.

You would have better luck setting up against a newer system integrated with your AD, such as Azure AD   or an on-prem ADFS server.

While that's certainly doable, it isn't trivial enough where I could describe how to do it in a simple issue ticket though.

**Comment by djkraz** [comment]
Has this changed at all?  We've been using ticket desk for years now and love it but we are at the point that we really need to upgrade to something more current.  That said, it must integrate with AD.  We are considering spiceworks and have looked at many others but none of them are simple and intuitive as ticket desk so I've been hesitant to make the switch.

**Comment by StephenRedd** [comment]
It has not changed. I'm evaluating what the future looks like for this application but right now no announcements to make. 

I do have a question though, if you don't mind. The AD integration is important to you, but are you in a position where you could use ADFS or Azure AD in conjunction with OpenID Connect, oAuth, or similar to do your integration? Or are you specifically dependent on straight on-prem AD integration like TD 2.1 supports?

**Comment by djkraz** [comment]
We do not use ADFS however we do have the Azure AD connector setup and it works great so that is definitely an option.

**Comment by StephenRedd** [comment]
@djkraz Thanks, that is helpful. There are apparently a lot of people still interested in AD integration, but I'd probably prefer to design modules for self-auth and federated identity first. Pure windows AD is problematic on the administration side -- and that hasn't gotten much easier with cross-platform .Net.

**Comment by JoeriBlootacker** [comment]
Also interested in ADFS here :) will be following this thread closely and if necessary more than willing to test stuff out
