### ISSUE TITLE
What should users be allowed to see?

### ISSUE THREAD

**Issue by btidoug** [NullDesk/ticketdesk#33]
Can we open a discussion on what the "user" group is actually allowed to see in the ticketdesk dashboard?  Staff should probably be able to see all tickets or all that are assigned to them.  Admins obviously should see them all.

My question is ultimately about the users and what all they can see in the dashboard.  Should a user only be able to see "their" tickets or tickets created for them?  Should a user be able to see all tickets and all comments and all discussions and all attachments?

I would like to lean toward restricting users to only being able to view their tickets.

**Comment by StephenRedd** [comment]
Sure. Eventually, we'll have time to write this up in the wiki too. 

The TicketDesk 1 and 2 products are designed primarily for internal help desk usage scenarios. The assumption with internal scenarios is that there is a reasonable level of trust between the users. In fact, the whole point of TicketDesk is built around trusting your users, and encouraging an ongoing conversation with them. 

## Internal User Focus

Because of the internal user focus, TicketDesk doesn't hide information from your users. This philosophy manifests primarily in these two ways. 

- **Information Sharing and Visibility**: 

 Users are able to see any ticket in the system. When a user has a problem, they can look at other tickets to see if the problem has been reported yet, and even jump in with "me-too" comments if there is already a ticket for their issue. This may help reduce duplicate tickets. Users can also search ticket history to see if a problem has happened in the past, and maybe they can find a resolution in the activity history and not need to submit a new issue. 

- **Ticket Activities**:

 In general, it treats users like mature adults. TicketDesk is for sharing information and communicating with your users with as little friction as possible. It doesn't try to get in involved in your organizations politics, and it doesn't try to act as a policy-cop. If you have things you'd rather your users not do in the system, just tell them... you'll be surprised at how well that works. 

 There are behavioral differences between the roles in ticketdesk. Staff have access to activities and views that regular users don't. The owner or a ticket will have access to activities that non-owners will not. And the assigned staff member will have access to different activities than other staff users. But, these behavioral differences have little do with permissions or policy enforcement. 

 What a user can do depends on what makes sense given their role, their relationship to the ticket, and the present state of that ticket. What a user can do does NOT depend on company policy or organization charts. 

 The distinctions between what different users are allowed to do correlates with security policy at most organizations, but this correlation is just incidental. As an example: Only staff users can assign a ticket to another staff user. This may seems like a permission type behavior, but it isn't. The reason this rule is enforced in TicketDesk is because it does't make business sense for a non-staff member to ever need or want to assign a ticket --so the assign function just isn't presented as an option. TicketDesk's design never assumed that your organization may have some security policy that specifies that users will face formal disciplinary action from management if they assign or reassign a ticket. 

## Low-Trust Environments:
----

 TicketDesk can be used in other environments besides internal help desks, but there are often conflicting requirements, especially with users external to your organization or who are customers. TicketDesk makes internal help desks better by encouraging information sharing and user-to-user communication, but low-trust situations need an inversion of these design principals. TicketDesk 2x doesn't directly address those scenarios, so you should evaluate carefully if you can make it work in your particular case. 

 TicketDesk 3 will address these issues with a set of features aimed specifically at external user and customer support scenarios. Obviously, the first step in supporting those scenarios is to introduce a formalized notion of permissions, customizable user roles, permission sets, etc. However, TicketDesk 3's design will be very careful to make sure that these additional administrative complexities do not over-complicate administration for organizations only using the internal user feature set.
