### ISSUE TITLE
Mono Support

### ISSUE THREAD

**Issue by BrendanThompson** [NullDesk/TicketDesk#81]
@StephenRedd would be good to see some Mono support here so that the application can be deployed out to a simple _DigitalOcean droplet_ for example. Although, it would then probably also have the requirement of being able to use more than just an MSSQL DB.

**Comment by StephenRedd** [comment]
I'll be honest, I have nearly zero experience with mono. I read up on it from time-to-time, but have never had the time, nor a pressing need, to work with it directly. So I couldn't say for sure how much would need to be changed to run TD on mono currently. 

From what I read though, the TD 2.5 code-base should be very nearly mono capable already. It is built on the OWIN/Katana stack, and most of the dependencies are latest generation self-contained nuget packages --and from what I can tell, most of those should be mono friendly. 

There may be a need to refactor some of the async controllers, since mono seems to only have partial support for those, and the HostingEnvrionment.QueueBackgroundWorkItem method from .Net 4.5.2 might need a custom implementation (which should be simple enough to hand-code).

Otherwise though, I don't see much that isn't on mono's compatibility lists. 

We do have plans to port TicketDesk up to the .Net Core 5.0 framework later this fall, assuming .Net core contains enough functionality to meet all of TicketDesk's requirements. This should would TicketDesk run across all the major platforms. While it isn't targeting mono specifically, it should enable the DigitalOcean scenario you mentioned, as well as Docker and similar container virtualization environments. If Mono keeps pace with .Net Core 5 and DNX, that port might run as-is on mono as well. 

Where I'm less sure about a port is EntityFramework 7. EF 7 is shaping up to be amazing, the first-cut has some limitations --they scaled back the initial feature set a good bit. I'm concerned about the lack of lazy loading, the loss of E-SQL (which TicketDesk leverages for filtering), and the radical changes in how migrations are handled.  

We may be forced to wait until the next EF version to move up from EF 6, and I'm not yet sure how, or if, remaining on EF 6 might limit cross-platform capabilities with DNX and .Net Core 5. 

I have a good bit of experimentation and research to do, but I'm waiting on the RTM bits for ASP.NET 5, .Net Core 5, and Visual Studio 2015 before I dive too deeply into prototypes.

**Comment by BrendanThompson** [comment]
Wonderful, yeah I was more actually talking about the DNX stuff. Most of the time easier to reference Mono as it's what most people think when they hear .NET not on windows :). This is all sound fantastic though!

**Comment by StephenRedd** [comment]
This version of TicketDesk will ship and go to end-of-life on the .Net 4x framework. 

ASP.NET Core 1.0 support will be done in a future version (TD3). Due to the massive change in both back and front-end planned, that development will be done as a re-write under a new git repository entirely.
