### ISSUE TITLE
TicketType having custom states

### ISSUE THREAD

**Issue by saikovvuri** [NullDesk/ticketdesk#84]
Hello, 

first of all kudos to an awesome product. Does ticketdesk support custom states based on ticketType. 
Like a problem ticket having custom workflow etc. 

Thanks

**Comment by StephenRedd** [comment]
No. TicketDesk very deliberately has a super-simple static workflow. Active, resolved, done. Even the current 'more info' flow is more complex than is ideal (see #21). 

The entire point of the system is to keep the workflow consistent, and so simple that the behavior is obvious to any user, without training, and without administrative overhead.

There are some plans to potentially introduce a very small number of workflow admin options (probably in the TD 3 timeframe).

One is an option to skip the resolve state and go straight from active to closed. Useful for purely internal scenarios where 'user' and 'staff' roles represent the same set of users. 

Another option would be to allow users to rename existing states, and potentially add any number of additional states. IN this case though, all states would still be arranged in a linear flow. The admin would need to specify who (owner or assigned users) is the 'actor' responsible for transitioning tickets out of that state. Basically, this proposal would be needed to support a kanban-style UI and associated linear workflow.

Anyway, there are no plans to introduce rule based workflows. They come with a heavy administrative overhead, complicate the coding enormously, and make the system less intuitive and less efficient for the vast majority of users. 

In general, whenever someone asks for a rule based flow, I ask instead what specific problem they are trying to solve within their organization. In every case I've encountered so far, rule based flows were not the most effective solution... they were just the most obvious. 

Of course, one day I'll probably encounter a real business case for which a rule based workflow really is the best solution. 

Can you explain a little more what particular business need made you ask? Maybe TicketDesk is just missing a feature that would let you achieve the goal without a complex custom rules engine.

**Comment by saikovvuri** [comment]
Hi Stephen, 

We have two requirements regarding ticket types - 
1. Centered around Due Date and Clock Start Date -  The business users believe that they need a mechanism to configure when does the clock on ticket actually start. For e.g. on a ticket type "Incident" clock starts as soon as it comes into helpdesk queue. On ticket type "Software Request", clock starts when it is assigned to a resource.
2. Each Ticket Type has its own workflow, some have states that do not apply to other types. Something on those lines. 

Regards

**Comment by StephenRedd** [comment]
Thanks for the extra info, and I'm glad you expanded on this because the due date feature is near implementation, and this may slightly alter how I implement it.

Lets take these in reverse order:

2. This is a functional requirement, but the description doesn't provide the business justification behind it. I couldn't say if the functional requirement is valid or not. There are issue tracker scenarios where this kind of functional requirement is strongly justified (enterprise project trackers for example). 

TicketDesk's implementation of worlkflow is so trivial that there isn't even a formal code model or architectural concept that defines 'workflow'. There is only a status field, and it has no direct business rule behavior associated with it. 

The implementation of several other functional requirements are contingent on the status value, which has the effect of creating a weak notion of workflow, but only as an incidental by-product.

If you were to model distinct differences in workflow based on additional fields (such as Ticket Type), then TicketDesk would benefit from a more formal model to encapsulate workflow related behaviors (a workflow engine). That could be done, but it would some significant refactoring.

Before you consider coding something like that, you'd want a compelling set of business requirements, and make sure there weren't less invasive ways to meet those requirements.

1. This one is easier. Other than due date, the description of the requirements identifies only existing data-points around which the behavior can be implemented. The behavior itself is limited to the aggregate time reporting itself, and doesn't appear to have any impact on other functional areas of the system.

There are two ways I can see your users consuming the aggregate, which I'll call "resolution time" from here out. It could be displayed on screen in ticket details or ticket center list views, or it could be part of the output of a report. 

In either case though, the value for this aggregate can be computed at runtime. You would need two dates. The end-date would always come from the due date field. The start date would come from the EventDate value on one of the TicketEvent entities associated with the ticket. Which TicketEvent to use is the only variable, contingent on the TicketType value. The logic would look something like this:

    DateTime endDate = Ticket.DueDate;
    TicketEvent clockStartEvent;
    If( Ticket.TicketType == "Incident")
    {
        clockStartEvent = Ticket.TicketEvents.First(e => e.TicketActivity == TicketActivity.Create || e.TicketActivity == TicketActivity.CreateOnBehalfOf); 
    }
    else if(Ticket.TicketType == "Software Request")
    {
        clockStartEvent = Ticket.TicketEvents.First(e => 
            e.TicketActivity == TicketActivity.Assign ||
            e.TicketActivity == TicketActivity.TakeOver );
    }
    TimeSpan resolutionTime = endDate - clockStartEvent.EventDate; 


This is a rough example. Since the possible values for ticket type are user configurable, it wouldn't quite be this simple, but hopefully it illustrates the technique.

The point is that the result can be achieved by encapsulating the business logic within the components of the system that care about the rule, without any impact on other areas of the system. In this case, we don't even need new data fields; everything we need can be inferred from data already present.

Now... consider a hypothetical: Lets suppose we did have multiple workflows, and a workflow rules engine. Also suppose we have a persistent data field on ticket for storing both due date and clock start date. Then suppose each workflow had a different rule for when and how to set the clock start data field. We get the same result, but  what happens when a user changes the TicketType field? 

Using the encapsulated calculation I described above, the output for resolution time magically accounts for any changes. With a workflow engine, we'd have to define and code dependent rules for every possible state change that might affect the parent rule. Now imagine a workflow rules engine applied across the entire set of behaviors ticketdesk implements (though it is a small list of behaviors). Further, imagine what happens when someone wants to let the admin custom define their own rules.

That's why I avoided workflow engines like the plague when I designed TicketDesk. They can be very powerful features, but it also takes an army of developers to design, test, and debug systems that use them.

**Comment by saikovvuri** [comment]
Thanks Stephen.  Really appreciate your deep dive analysis which would help me make business team explain that this is more of a implementation detail. 

Do you mind sharing some of the due date functionality.

**Comment by StephenRedd** [comment]
No worries. Stuff like this really helps me plan and design future features. 

I saw that you asked about more about due date over on #25, so I'll go into more detail over there --after dinner though :)

**Comment by saikovvuri** [comment]
Hey Stephen -  One edit to what we discussed. It just occured to me DueDate should not be a datetime but rather an offset from the calculated clock start time. 

If the users would like to have an resolution time for 3 days (duedate offset) for both incident and software request. the helpdesk can pick up the software request later as the due date will be 3 days from the time it was assigned or taken over

Regards
