### ISSUE TITLE
Allow Email Test Send

### ISSUE THREAD

**Issue by jmbalanag** [NullDesk/TicketDesk#94]
I have entered the settings correctly (im using: smtp.gmail.com port: 587)

But when creating tickets/editing/updating data, no notification is sent out.

Can you please add an option to send test email to admin to check whether email is properly configured.

Thanks.

**Comment by krtezech** [comment]
Yes I was just wondering the same thing. Like "Test the connection" at least :-).

**Comment by StephenRedd** [comment]
Duplicates #52

**Comment by StephenRedd** [comment]
We will have a good set of diagnostic tools in the admin section for viewing email rendering, viewing push notification schedules and history, and sending test emails. 

Push notification delivery operates in one of two modes. When running on IIS there is a background worker thread with standard timer loop that evaluates when to send the emails. This is the same technique used in TicketDesk 2.1. When deployed as an Azure WebApp, delivery is handled by an Azure WebJob instead.

In the future we will likely include an option to use a database synchronized scheduler such as Hangfire instead of a regular timer-loop.

**Comment by UMAIR2282** [comment]
Which settings are necessary for enabling Push Notifications?
