### ISSUE TITLE
Email Validation issue

### ISSUE THREAD

**Issue by prasadnadendla** [NullDesk/TicketDesk#97]
Email id is not validating properly while logging in. I know it's a small issue but i feel it's good if proper validation is happening so that others no need to think  about changing existing validation

**Comment by Oxymoron290** [comment]
How do I reproduce this issue?

**Comment by StephenRedd** [comment]
I'm not sure if this is a report about the email textbox not validating the format of the email typed, or if this is a request to add two step email verification (send an email on registration and require the user click a link back to verify the email address was legit before enabling the account). 

The former case seems to be working, but if I track back to August in the change history I might find that I'd not put the validation on that field until after this issue was reported. 

The latter case would be nice, but I had no plans to implement address validation just yet. In the next release cycle we'd plan to gut the entire security system and replace it, probably with something build from IdentityServer.
